dataset_path: images_dir
train_data_path: train_set
test_data_path: test_set
resume: False
epochs: 10
batch_size: 4
num_labels: 3
logging_config: logging.conf
output_logs_path: ./logs
output_ckpt_path: ./models
output_production_path: ./weights
device:
# Optimizer oparameters
learning_rate: 0.00005
scheduler_step: 2
scheduler_decay: 0.5

# Cross-validation
folds: 5